- name: create ec2 instance and route53
  hosts: local
  connection: local
  vars:
    ami_id: mi-09c813fb71547fc4f
    sg_id: sg-07e183e8018b9fafa
    zone_id: "Z07313947YY790RTUIWI"
    domain_name: "krishna.icu"
    instance:
    - mongodb

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ami_id }}"
      tags:
        name: "{{ item }}"
    loop: "{{ instance }}"
    register: ec2_output

  - name: print the ec2 output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"