- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: disable default nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: enable nginx 1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove the deafult html content
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html/

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory
  
  - name: download frontend application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: extract catalogue application
    ansible.builtin.unarchive: #unzip file 
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: remove nginx configation
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf

  - name: copy frontend service
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart ngnix 
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes